.PHONY: clean All

All:
	@echo "----------Building project:[ LogOS - Linux ]----------"
	@"$(MAKE)" -f  "LogOS.mk" && "$(MAKE)" -f  "LogOS.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ LogOS - Linux ]----------"
	@"$(MAKE)" -f  "LogOS.mk" clean
